apiVersion: v2
name: cnpg-connect-plugin
description: CloudNativePG role and topology discovery with a streaming API
type: application
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.30.0-0"
home: https://github.com/nakiner/cnpg-connect-plugin
sources:
  - https://github.com/nakiner/cnpg-connect-plugin
