// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: cnpg/connect/v1/topology.proto

package connectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyService_GetTopology_FullMethodName   = "/cnpg.connect.v1.TopologyService/GetTopology"
	TopologyService_WatchTopology_FullMethodName = "/cnpg.connect.v1.TopologyService/WatchTopology"
)

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TopologyService discovers individual PostgreSQL instances. Both methods
// require Authorization: Bearer <token> metadata when authentication is enabled.
// TLS and authentication are configured by the deployment, not this protocol.
type TopologyServiceClient interface {
	// Returns the complete current observation, including unavailable/expired
	// snapshots. An unknown or deleted cluster returns NOT_FOUND.
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*Snapshot, error)
	// Atomically subscribes and sends a complete initial snapshot, followed by
	// complete refreshes. Unknown clusters return NOT_FOUND. Existing watchers
	// receive deletion tombstones and can observe same-name recreation.
	// Slow consumers may miss intermediate states. Reconnect by subscribing again;
	// every reconnect starts with a complete snapshot, never a delta or replay.
	WatchTopology(ctx context.Context, in *WatchTopologyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error)
}

type topologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyServiceClient(cc grpc.ClientConnInterface) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, TopologyService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyServiceClient) WatchTopology(ctx context.Context, in *WatchTopologyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyService_ServiceDesc.Streams[0], TopologyService_WatchTopology_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTopologyRequest, Snapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_WatchTopologyClient = grpc.ServerStreamingClient[Snapshot]

// TopologyServiceServer is the server API for TopologyService service.
// All implementations must embed UnimplementedTopologyServiceServer
// for forward compatibility.
//
// TopologyService discovers individual PostgreSQL instances. Both methods
// require Authorization: Bearer <token> metadata when authentication is enabled.
// TLS and authentication are configured by the deployment, not this protocol.
type TopologyServiceServer interface {
	// Returns the complete current observation, including unavailable/expired
	// snapshots. An unknown or deleted cluster returns NOT_FOUND.
	GetTopology(context.Context, *GetTopologyRequest) (*Snapshot, error)
	// Atomically subscribes and sends a complete initial snapshot, followed by
	// complete refreshes. Unknown clusters return NOT_FOUND. Existing watchers
	// receive deletion tombstones and can observe same-name recreation.
	// Slow consumers may miss intermediate states. Reconnect by subscribing again;
	// every reconnect starts with a complete snapshot, never a delta or replay.
	WatchTopology(*WatchTopologyRequest, grpc.ServerStreamingServer[Snapshot]) error
	mustEmbedUnimplementedTopologyServiceServer()
}

// UnimplementedTopologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyServiceServer struct{}

func (UnimplementedTopologyServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedTopologyServiceServer) WatchTopology(*WatchTopologyRequest, grpc.ServerStreamingServer[Snapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchTopology not implemented")
}
func (UnimplementedTopologyServiceServer) mustEmbedUnimplementedTopologyServiceServer() {}
func (UnimplementedTopologyServiceServer) testEmbeddedByValue()                         {}

// UnsafeTopologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyServiceServer will
// result in compilation errors.
type UnsafeTopologyServiceServer interface {
	mustEmbedUnimplementedTopologyServiceServer()
}

func RegisterTopologyServiceServer(s grpc.ServiceRegistrar, srv TopologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTopologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyService_ServiceDesc, srv)
}

func _TopologyService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyService_WatchTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTopologyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).WatchTopology(m, &grpc.GenericServerStream[WatchTopologyRequest, Snapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_WatchTopologyServer = grpc.ServerStreamingServer[Snapshot]

// TopologyService_ServiceDesc is the grpc.ServiceDesc for TopologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cnpg.connect.v1.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopology",
			Handler:    _TopologyService_GetTopology_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTopology",
			Handler:       _TopologyService_WatchTopology_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cnpg/connect/v1/topology.proto",
}
