// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cnpg/connect/v1/topology.proto

package connectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNKNOWN Role = 0
	Role_ROLE_PRIMARY Role = 1
	Role_ROLE_STANDBY Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_PRIMARY",
		2: "ROLE_STANDBY",
	}
	Role_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"ROLE_PRIMARY": 1,
		"ROLE_STANDBY": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_cnpg_connect_v1_topology_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_cnpg_connect_v1_topology_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{0}
}

type SyncState int32

const (
	SyncState_SYNC_STATE_UNKNOWN   SyncState = 0
	SyncState_SYNC_STATE_SYNC      SyncState = 1
	SyncState_SYNC_STATE_QUORUM    SyncState = 2
	SyncState_SYNC_STATE_POTENTIAL SyncState = 3
	SyncState_SYNC_STATE_ASYNC     SyncState = 4
)

// Enum value maps for SyncState.
var (
	SyncState_name = map[int32]string{
		0: "SYNC_STATE_UNKNOWN",
		1: "SYNC_STATE_SYNC",
		2: "SYNC_STATE_QUORUM",
		3: "SYNC_STATE_POTENTIAL",
		4: "SYNC_STATE_ASYNC",
	}
	SyncState_value = map[string]int32{
		"SYNC_STATE_UNKNOWN":   0,
		"SYNC_STATE_SYNC":      1,
		"SYNC_STATE_QUORUM":    2,
		"SYNC_STATE_POTENTIAL": 3,
		"SYNC_STATE_ASYNC":     4,
	}
)

func (x SyncState) Enum() *SyncState {
	p := new(SyncState)
	*p = x
	return p
}

func (x SyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_cnpg_connect_v1_topology_proto_enumTypes[1].Descriptor()
}

func (SyncState) Type() protoreflect.EnumType {
	return &file_cnpg_connect_v1_topology_proto_enumTypes[1]
}

func (x SyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncState.Descriptor instead.
func (SyncState) EnumDescriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{1}
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopologyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTopologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTopologyRequest) Reset() {
	*x = WatchTopologyRequest{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopologyRequest) ProtoMessage() {}

func (x *WatchTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopologyRequest.ProtoReflect.Descriptor instead.
func (*WatchTopologyRequest) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{1}
}

func (x *WatchTopologyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchTopologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClusterRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRef) Reset() {
	*x = ClusterRef{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRef) ProtoMessage() {}

func (x *ClusterRef) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRef.ProtoReflect.Descriptor instead.
func (*ClusterRef) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterRef) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port  uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// TLS certificate identity when it differs from host.
	ServerName    string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes Pod UID: replacement changes identity even if name/address stays.
	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role      Role      `protobuf:"varint,3,opt,name=role,proto3,enum=cnpg.connect.v1.Role" json:"role,omitempty"`
	SyncState SyncState `protobuf:"varint,4,opt,name=sync_state,json=syncState,proto3,enum=cnpg.connect.v1.SyncState" json:"sync_state,omitempty"`
	Ready     bool      `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason    string    `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Network name -> directly reachable endpoint (internal, optional external).
	Endpoints     map[string]*Endpoint `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Node          string               `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`
	Zone          string               `protobuf:"bytes,9,opt,name=zone,proto3" json:"zone,omitempty"`
	Region        string               `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Timeline      int64                `protobuf:"varint,11,opt,name=timeline,proto3" json:"timeline,omitempty"`
	ReplayLsn     string               `protobuf:"bytes,12,opt,name=replay_lsn,json=replayLsn,proto3" json:"replay_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{4}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

func (x *Member) GetSyncState() SyncState {
	if x != nil {
		return x.SyncState
	}
	return SyncState_SYNC_STATE_UNKNOWN
}

func (x *Member) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Member) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Member) GetEndpoints() map[string]*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Member) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Member) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Member) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Member) GetTimeline() int64 {
	if x != nil {
		return x.Timeline
	}
	return 0
}

func (x *Member) GetReplayLsn() string {
	if x != nil {
		return x.ReplayLsn
	}
	return ""
}

type Snapshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Cluster    *ClusterRef            `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Opaque and restart-safe. Changes on routing/identity changes, not on mere
	// freshness refreshes or replay LSN changes. Never compare numerically.
	Revision   string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Clients MUST reject expired routing even if the stream remains connected.
	// Transport keepalives do not extend this deadline.
	ValidUntil    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	PrimaryId     string                 `protobuf:"bytes,8,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	Transitioning bool                   `protobuf:"varint,9,opt,name=transitioning,proto3" json:"transitioning,omitempty"`
	Members       []*Member              `protobuf:"bytes,10,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cnpg_connect_v1_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_cnpg_connect_v1_topology_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Snapshot) GetCluster() *ClusterRef {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *Snapshot) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *Snapshot) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Snapshot) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Snapshot) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Snapshot) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Snapshot) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *Snapshot) GetTransitioning() bool {
	if x != nil {
		return x.Transitioning
	}
	return false
}

func (x *Snapshot) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_cnpg_connect_v1_topology_proto protoreflect.FileDescriptor

const file_cnpg_connect_v1_topology_proto_rawDesc = "" +
	"\n" +
	"\x1ecnpg/connect/v1/topology.proto\x12\x0fcnpg.connect.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x12GetTopologyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x14WatchTopologyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\n" +
	"ClusterRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\"S\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\"\xda\x03\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04role\x18\x03 \x01(\x0e2\x15.cnpg.connect.v1.RoleR\x04role\x129\n" +
	"\n" +
	"sync_state\x18\x04 \x01(\x0e2\x1a.cnpg.connect.v1.SyncStateR\tsyncState\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12D\n" +
	"\tendpoints\x18\a \x03(\v2&.cnpg.connect.v1.Member.EndpointsEntryR\tendpoints\x12\x12\n" +
	"\x04node\x18\b \x01(\tR\x04node\x12\x12\n" +
	"\x04zone\x18\t \x01(\tR\x04zone\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x1a\n" +
	"\btimeline\x18\v \x01(\x03R\btimeline\x12\x1d\n" +
	"\n" +
	"replay_lsn\x18\f \x01(\tR\treplayLsn\x1aW\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.cnpg.connect.v1.EndpointR\x05value:\x028\x01\"\xa6\x03\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x125\n" +
	"\acluster\x18\x02 \x01(\v2\x1b.cnpg.connect.v1.ClusterRefR\acluster\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12;\n" +
	"\vvalid_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"primary_id\x18\b \x01(\tR\tprimaryId\x12$\n" +
	"\rtransitioning\x18\t \x01(\bR\rtransitioning\x121\n" +
	"\amembers\x18\n" +
	" \x03(\v2\x17.cnpg.connect.v1.MemberR\amembers*<\n" +
	"\x04Role\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fROLE_PRIMARY\x10\x01\x12\x10\n" +
	"\fROLE_STANDBY\x10\x02*\x7f\n" +
	"\tSyncState\x12\x16\n" +
	"\x12SYNC_STATE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSYNC_STATE_SYNC\x10\x01\x12\x15\n" +
	"\x11SYNC_STATE_QUORUM\x10\x02\x12\x18\n" +
	"\x14SYNC_STATE_POTENTIAL\x10\x03\x12\x14\n" +
	"\x10SYNC_STATE_ASYNC\x10\x042\xb5\x01\n" +
	"\x0fTopologyService\x12M\n" +
	"\vGetTopology\x12#.cnpg.connect.v1.GetTopologyRequest\x1a\x19.cnpg.connect.v1.Snapshot\x12S\n" +
	"\rWatchTopology\x12%.cnpg.connect.v1.WatchTopologyRequest\x1a\x19.cnpg.connect.v1.Snapshot0\x01BAZ?github.com/nakiner/cnpg-connect-plugin/api/connect/v1;connectv1b\x06proto3"

var (
	file_cnpg_connect_v1_topology_proto_rawDescOnce sync.Once
	file_cnpg_connect_v1_topology_proto_rawDescData []byte
)

func file_cnpg_connect_v1_topology_proto_rawDescGZIP() []byte {
	file_cnpg_connect_v1_topology_proto_rawDescOnce.Do(func() {
		file_cnpg_connect_v1_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cnpg_connect_v1_topology_proto_rawDesc), len(file_cnpg_connect_v1_topology_proto_rawDesc)))
	})
	return file_cnpg_connect_v1_topology_proto_rawDescData
}

var file_cnpg_connect_v1_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cnpg_connect_v1_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cnpg_connect_v1_topology_proto_goTypes = []any{
	(Role)(0),                     // 0: cnpg.connect.v1.Role
	(SyncState)(0),                // 1: cnpg.connect.v1.SyncState
	(*GetTopologyRequest)(nil),    // 2: cnpg.connect.v1.GetTopologyRequest
	(*WatchTopologyRequest)(nil),  // 3: cnpg.connect.v1.WatchTopologyRequest
	(*ClusterRef)(nil),            // 4: cnpg.connect.v1.ClusterRef
	(*Endpoint)(nil),              // 5: cnpg.connect.v1.Endpoint
	(*Member)(nil),                // 6: cnpg.connect.v1.Member
	(*Snapshot)(nil),              // 7: cnpg.connect.v1.Snapshot
	nil,                           // 8: cnpg.connect.v1.Member.EndpointsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_cnpg_connect_v1_topology_proto_depIdxs = []int32{
	0,  // 0: cnpg.connect.v1.Member.role:type_name -> cnpg.connect.v1.Role
	1,  // 1: cnpg.connect.v1.Member.sync_state:type_name -> cnpg.connect.v1.SyncState
	8,  // 2: cnpg.connect.v1.Member.endpoints:type_name -> cnpg.connect.v1.Member.EndpointsEntry
	4,  // 3: cnpg.connect.v1.Snapshot.cluster:type_name -> cnpg.connect.v1.ClusterRef
	9,  // 4: cnpg.connect.v1.Snapshot.observed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: cnpg.connect.v1.Snapshot.valid_until:type_name -> google.protobuf.Timestamp
	6,  // 6: cnpg.connect.v1.Snapshot.members:type_name -> cnpg.connect.v1.Member
	5,  // 7: cnpg.connect.v1.Member.EndpointsEntry.value:type_name -> cnpg.connect.v1.Endpoint
	2,  // 8: cnpg.connect.v1.TopologyService.GetTopology:input_type -> cnpg.connect.v1.GetTopologyRequest
	3,  // 9: cnpg.connect.v1.TopologyService.WatchTopology:input_type -> cnpg.connect.v1.WatchTopologyRequest
	7,  // 10: cnpg.connect.v1.TopologyService.GetTopology:output_type -> cnpg.connect.v1.Snapshot
	7,  // 11: cnpg.connect.v1.TopologyService.WatchTopology:output_type -> cnpg.connect.v1.Snapshot
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cnpg_connect_v1_topology_proto_init() }
func file_cnpg_connect_v1_topology_proto_init() {
	if File_cnpg_connect_v1_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cnpg_connect_v1_topology_proto_rawDesc), len(file_cnpg_connect_v1_topology_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cnpg_connect_v1_topology_proto_goTypes,
		DependencyIndexes: file_cnpg_connect_v1_topology_proto_depIdxs,
		EnumInfos:         file_cnpg_connect_v1_topology_proto_enumTypes,
		MessageInfos:      file_cnpg_connect_v1_topology_proto_msgTypes,
	}.Build()
	File_cnpg_connect_v1_topology_proto = out.File
	file_cnpg_connect_v1_topology_proto_goTypes = nil
	file_cnpg_connect_v1_topology_proto_depIdxs = nil
}
